name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python Wheel
      run: pip install wheel
    - name: Install PlatformIO Core
      run: pip install -U https://github.com/platformio/platformio/archive/v4.2.1.zip
    - name: Copy generic config over
      run: cp config.example.h config.h
    - name: Compile Command Station (AVR)
      run: python -m platformio run
